### ISSUE TITLE
グループ一覧を隠した状態でボタンを押すとエラーが発生する

### ISSUE THREAD

**Issue by ruhiel** [andanteyk/ElectronicObserver#104]
軽微なものですが報告まで。
一覧を隠した状態でボタンを押下するとエラーが発生しました。

![default](https://cloud.githubusercontent.com/assets/6840095/21564681/9e619d6e-ced3-11e6-868a-9f6404f7ef71.png)

**Comment by andanteyk** [comment]
大変お待たせしました…
ご報告ありがとうございます。 3e82b3ee43156da9c3d549641e53682ecad85945 で修正しました。
次のバージョンから直るはずです。
