### ISSUE TITLE
Combined Fleet (連合艦隊) View

### ISSUE THREAD

**Issue by silfumus** [andanteyk/ElectronicObserver#109]
Please add a separate fleet view for combined fleet.

Since it's only used for combined fleet, several information such as equipment icons could be omitted to save UI space. The separate sub-window would also help users by calculating the combined fighter power and LOS rather than manually calculating from the separate fleet 1 and fleet 2 sub-window.

Below is an illustration of the fleet view if stacked horizontally, but stacked vertically is okay too.

![combinedfleetview](https://cloud.githubusercontent.com/assets/6127734/23336286/a94f507a-fbfd-11e6-89b9-ad034101254a.png)

**Comment by andanteyk** [comment]
この機能は、現状では必要性が薄いと考えます。
実装コストに見合わないと感じました。

理由は以下の通りです：

* 艦娘のパラメータ表示部分については、レイアウトを変更することで現状でも同等の表示が可能である。
	* 装備の非表示については、「スクロールバーを表示しない」設定を有効にしてウィンドウを並べることで再現できます
	* レイアウトを別のファイルにセーブすることで、通常表示と連合艦隊表示を切り替えることができます
* ほぼ同じコードを2回書かなければならない。
	* そうならないように設計するべきではありますが…
* パラメータ(制空値等)の合算表示については有用だと思うが、そのためにウィンドウを1つ増やす必要があるのか？
	* 制空値については 連合艦隊vs連合艦隊 の時のみ合算となり、連合艦隊vs通常艦隊 では依然として第一艦隊のもののみ適用されるため、一概に合算表示がいいとは言えません
	* 艦隊一覧(FleetOverview)ウィンドウのラベルのツールチップとして実装するかもしれません

---

I think that this function is not necessary at present.
I felt it was not suitable for implementation cost.

The detailed reasons are as follows:

* As for the parameter display part of the ship, the same display can be made even with the current program by changing the layout.
	* If you want to hide equipment view, enable "Do not show scroll bars" setting and arrange the windows.
	* By saving the layout in a separate file, you can switch between normal display and combined fleet mode display.
* I have to write almost the same code twice.
	* It should be designed so that it does not, of course ...
* *I think that it is useful to display summation of parameters (Fighter Power etc.)*, but I don't think there is a need to add windows for that.
	* For the Fighter Power, summation is effective at only "Combined Fleet vs. Combined Fleet" battle. First fleet's value is still used at "Combined Fleet vs. Normal Fleet" battle.
		Therefore, it can not be said that the summation display is always effective.
	* Summation display may be implemented as a tooltip at the label of FleetOverview window, instead of new window.

**Comment by silfumus** [comment]
I had been tinkering with the code before this issue and it was as you just explained, it is complex to implement. I appreciate your reply.
As always, thank you for your hard work!
