### ISSUE TITLE
レコード：デフォルトレコードの文字コード問題

### ISSUE THREAD

**Issue by andanteyk** [andanteyk/ElectronicObserver#116]
設定文字コードが shift-jis 以外の時、デフォルトレコードからの読み込みが正しく行われない

**Comment by RadarNyan** [comment]
I acturally had this fixed, forget to send a pull request: 0388965
(You may want to re-format the code)

**Comment by andanteyk** [comment]
Thank you for the information.
Based on the received code, I made fine adjustment and fixed it at 1d8d97e5d30410587ccee7af5f9e8b150dec4d5e.
