### ISSUE TITLE
Hope to add upstream proxy ip settings

### ISSUE THREAD

**Issue by gy6221** [andanteyk/ElectronicObserver#12]
Hello, can you add an ip address settings of upstream proxy server?

Sometimes we may use an remote proxy server instead of local.

**Comment by andanteyk** [comment]
Sorry for my late reply.
You can do it with changing `UpstreamProxyAddress` in configuration file (Configuration.xml).
I can't guarantee whether it is running properly because I don't have a way to test it.
It doesn't have on the GUI, because I think it is not necessary in normal use.
