### ISSUE TITLE
ブラウザ：SSのクリップボードへのコピーに失敗することがある

### ISSUE THREAD

**Issue by andanteyk** [andanteyk/ElectronicObserver#139]
https://twitter.com/Nishisonic/status/887986831966453760
https://msdn.microsoft.com/ja-jp/library/system.windows.forms.clipboard.setimage(v=vs.110).aspx

別のプロセスに占有されていてクリップボードがクリアできないのが原因らしい
解決できないとしてもエラーメッセージを改善すべき

**Comment by CNA-Bld** [comment]
I have met this problem several times when using setImage, setText etc.

The source code shows that by default it will retry for 10 times with 100ms delay each and only when all of them failed the exception will be thrown. https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Clipboard.cs,100

However usually the data is actually successfully set even if this exception happens. I was not successful trying to find a clean fix so I agree that maybe the best we can do is to display a better error message.

**Comment by andanteyk** [comment]
根本的な解決にはなっていないが、0d3b706fd725ccca754abd4b2d5a1814d1fa0ceb で以下の変更を行った。

* 当該箇所のエラーメッセージの短縮
* 改行を含むログが出た時に、ステータスバーの表示が複数行にならないように
