### ISSUE TITLE
v2.7.1: The fatigue icon does not restore in fleet tab

### ISSUE THREAD

**Issue by leeyc0** [andanteyk/ElectronicObserver#143]
![default](https://user-images.githubusercontent.com/2221335/29052564-8f64021e-7c1d-11e7-81e2-7515c0f29825.PNG)

As shown in screenshot, the  fatigue icon in fleet tab does not restore when morale raises back.

**Comment by andanteyk** [comment]
Thank you for your report.
I fixed this problem at 75c2724c1542cfddec13ee7620708dd283b099ce.
