### ISSUE TITLE
任務：「任務名で検索」が欲しい

### ISSUE THREAD

**Issue by ekicyou** [andanteyk/ElectronicObserver#144]
任務→任務名の欄を右クリック→「任務名で検索」が出来ると単発任務の情報がgoogle検索される、ような機能が欲しい。不明情報について「（任務名）　艦これ」で検索するとたいてい何とかなるので、特に単発クエスト系で助かります。

任務以外にも、艦名・装備名の検索があると非常にありがたいです。

**Comment by andanteyk** [comment]
とてもいいアイディアだと思います。
11bcf12ac8dfacae668b4fd93ab4821d64ef4ebf　で実装しました、問題が起きなければ次のバージョンで使用可能になります。

**Comment by ekicyou** [comment]
早速の実装、有難うございます！
攻略には検索を多用しますので助かります。
