### ISSUE TITLE
Calling Font.Dispose() in custom controls breaks the Font

### ISSUE THREAD

**Issue by CNA-Bld** [andanteyk/ElectronicObserver#167]
ed2763ec5ce14f0f50d66af0796b23d1d8cb7bc8 adds calls to `Font.Dispose()` in `ShipStatusHP`, `ShipStatusLevel`.

However, `_mainFont` and `_subFont` in these two classes are shared instances used by both of them, `StatusStrip` and somewhere internally in DockPanelSuite. Disposing the shared instance might cause other components to misbehave.

I cannot find an existing crash caused by this, but it can be observed by:
* Add a breakpoint in `ShipStatusHP.cs`, line 513 (`_mainFont?.Dispose();`) is a good choice;
* Open 設定 and navigate to UI panel (because there is an HP bar);
* Click キャンセル to close the window (cannot use OK as that will trigger `ConfigurationChanged`);
* `ShipStatusHP.Dispose` triggers the breakpoint. Evaluating `_mainFont.Height` etc. should work properly;
* Open 設定 and navigate to UI panel again, click キャンセル again;
* The breakpoint is triggered again. Now evaluating `_mainFont.Height` throws an exception.

This does not currently cause problems because Microsoft made some hacks to `Font` so most controls will still work even if its `Font` is already disposed. This is because `Font` is immutable and people tend to reuse them so they are very likely to be disposed at some random place. Even MS-written WinForms controls do not `Clone` / `Dispose` them either. [Ref]

However this might cause problem if the same instance is used again (even calling `.Height` or `MeasureWidth` will crash the program). (And it's anyways bad for a class to dispose something not created by it.)

We have 2 solutions to solve this:
* Use `Font.Clone()` in the setters of the two controls;
* Don't dispose them.

I really don't know which one is better as MS does not have a clear convention on this. (To be honest `IDisposable` is really a terrible design.) I think you can make the decision so submitted this as an issue instead of a PR.

[Ref]: https://stackoverflow.com/a/22665651/1676435

**Comment by andanteyk** [comment]
Thank you for your report.
I also confirmed that an error occurred.
(In addition to the above method, when I looked at the "Output" window in Visual Studio, I noticed that an exception occurred every time display was updated.)

In such a case, I would like to make it a policy **not to use** `Dispose()`.
I fixed `ShipStatusHP` and `ShipStatusLevel` at eaa0bcee3df2c0478a8f23d4bcba8c2264e6ad80.

**Comment by andanteyk** [comment]
As far as I confirmed, no problems were found outside these two classes.
I will close this ticket once. If there are other similar problems, please report again.
Again, thank you for your report.
