### ISSUE TITLE
連合艦隊関連の不具合

### ISSUE THREAD

**Issue by RadarNyan** [andanteyk/ElectronicObserver#182]
今回の秋イベ E-3 攻略中で発見したものです。

**1. 戦闘：味方が連合艦隊の場合、敵旗艦（連合艦隊時主力艦隊旗艦）のＨＰバーが消える**

```ElectronicObserver/Window/FormBattle.cs``` に友軍護衛艦隊（```// friend escort```）の ```DisableHPBar(refindex);``` より消されました。

参照：
https://github.com/RadarNyan/ElectronicObserver/commit/f13bc7c6c31caef8a56d42b51a81f8dd5867be78#diff-c60e93f99d6d0f0cd4dff087751b6133

**2. 連合艦隊対連合艦隊の場合、夜戦入る時にエラー発生**

```ElectronicObserver/Data/Battle/BattleEnemyCombinedNight.cs``` に ```NightBattle.IsFriendEscort``` をチェックする時にエラー発生。

一時の回避策（上記と同じ commit）：
https://github.com/RadarNyan/ElectronicObserver/commit/f13bc7c6c31caef8a56d42b51a81f8dd5867be78#diff-672cabf597cb00a153ddffb688048697

ここで ```NightBattle``` が ```null``` になる原因は未調査。

**3. 連合艦隊と関係ないが、API 仕様変更により、基地防空戦にエラー発生**

```api_squadron_plane -> api_map_squadron_plane```

```null``` になる可能性あり（防空部隊なし）、要チェック

参照：
https://github.com/RadarNyan/ElectronicObserver/commit/5da3e05b2b81e3e24b00480f9a0a3939bbbf01a1

**Comment by ForsakenRei** [comment]
[20171122_14364607.txt](https://github.com/andanteyk/ElectronicObserver/files/1497290/20171122_14364607.txt)

Error report at E3, hope this helpful.

**Comment by andanteyk** [comment]
Thank you for the information. very helpful.
I am currently working on correcting it.

**Comment by andanteyk** [comment]
2. について：

`BattleEnemyCombinedNight.LoadFromResponse` → `PhaseNightBattle.ctor` → `PhaseBase.IsFriendCombined` → `BattleEnemyCombinedNight.BattleTypeFlag` → `NightBattle.IsFriendEscort` 
ここで、まだ `PhaseNightBattle.ctor` までしか処理していないため、`NightBattle == null` になります。
設計ミスです、すみません…

**Comment by andanteyk** [comment]
すべて修正できたので、いったん閉じます。何か問題があれば新しい issue を立ててください。
ご報告ありがとうございました。
