### ISSUE TITLE
'18 冬イベ対応関連

### ISSUE THREAD

**Issue by andanteyk** [andanteyk/ElectronicObserver#199]
### 友軍艦隊攻撃

夜戦で自軍艦隊以外の支援が飛んでくる　今のところE-4ボスで確認
active deck 決定前に攻撃フェーズが挟まる
> 具体的には、**友軍艦隊攻撃**→味方本隊表示→夜間触接→戦闘糧食発動→探照灯/照明弾演出→支援攻撃→夜戦

通常の夜間砲撃戦と同じ流れ
友軍艦隊 -> 敵全体、敵本隊？ -> 友軍艦隊
普通に攻撃も受けるし大破で行動不能になる、ただし中破演出はない（グラフィックには反映される）

> 攻撃されない場合あり？要確認

以下頂いたデータより更新

```
(省略)
api_eParam_combined		：[][4]

api_friendly_info	：友軍艦隊攻撃情報　発動時のみ存在
	api_production_type	：1=?
	api_ship_id		：友軍の艦船ID [艦船数]
	api_ship_lv		：友軍のLv [艦船数]
	api_nowhps		：友軍の現在HP [艦船数]
	api_maxhps		：友軍の最大HP [艦船数]
	api_Slot		：友軍の装備スロット [艦船数][5] 空きスロットは -1
	api_Param		：友軍の基礎ステータス [艦船数][4]; [火力, 雷装, 対空, 装甲]
	api_voice_id		：再生されるボイスID? [艦船数]
	api_voice_p_no		：1=戦闘前口上あり? [艦船数]
api_friendly_battle	：友軍艦隊攻撃　発動時のみ存在？
	api_flare_pos		：照明弾投射艦インデックス　[2]
	api_hougeki		：友軍艦隊攻撃　基本的に自軍夜戦と同じ
		api_at_eflag		：[]
		api_at_list		：[]
		api_n_mother_list	：[]
		api_df_list		：[][]
		api_si_list		：[][]
		api_cl_list		：[][]
		api_sp_list		：[]
		api_damage		：[][]

api_active_deck			：[2]
(省略)
```

### 難易度「丁」実装

インデックスが 1=丁, 2=丙, ... という感じにずれたらしい

### 武蔵改二

5スロット　対応はしているはずだがどこかで問題が出る可能性？
固有対空カットインあり？

**Comment by Nishisonic** [comment]
E-4甲 ボスマス 英仏支援 json

{"api_result":1,"api_result_msg":"成功","api_data":{"api_deck_id":1,"api_formation":[14,14,3],"api_f_nowhps":[22,14,53,2,62,22],"api_f_maxhps":[105,97,90,89,68,62],"api_f_nowhps_combined":[2,44,61,13,49,37],"api_f_maxhps_combined":[48,53,64,41,49,37],"api_fParam":[[139,0,104,118],[138,0,93,116],[98,0,84,94],[96,0,92,93],[56,0,87,74],[55,0,86,75]],"api_fParam_combined":[[36,0,48,19],[70,79,74,69],[77,84,106,78],[59,99,59,59],[63,139,49,63],[59,89,59,59]],"api_ship_ke":[1788,1780,1558,1558,1567,1567],"api_ship_lv":[1,1,1,1,1,1],"api_ship_ke_combined":[1595,1595,1743,1743,1743,1743],"api_ship_lv_combined":[1,1,1,1,1,1],"api_e_nowhps":[399,0,0,0,0,0],"api_e_maxhps":[650,118,130,130,130,130],"api_e_nowhps_combined":[0,0,0,0,0,0],"api_e_maxhps_combined":[88,88,66,66,66,66],"api_eSlot":[[581,582,583,580,-1],[581,582,583,575,-1],[506,504,504,-1,-1],[506,504,504,-1,-1],[509,509,529,526,-1],[509,509,529,526,-1]],"api_eSlot_combined":[[505,505,515,525,-1],[505,505,515,525,-1],[501,501,570,-1,-1],[501,501,570,-1,-1],[501,501,570,-1,-1],[501,501,570,-1,-1]],"api_eParam":[[188,160,128,278],[48,0,68,93],[55,0,40,65],[55,0,40,65],[110,0,88,110],[110,0,88,110]],"api_eParam_combined":[[79,74,79,89],[79,74,79,89],[79,113,86,63],[79,113,86,63],[79,113,86,63],[79,113,86,63]],"api_friendly_info":{"api_production_type":1,"api_ship_id":[364,393,392,519],"api_ship_lv":[86,85,62,40],"api_nowhps":[82,71,89,15],"api_maxhps":[82,71,89,15],"api_Slot":[[190,190,190,191,-1],[244,243,242,242,-1],[245,245,247,-1,-1],[280,280,260,-1,-1]],"api_Param":[[93,0,66,84],[35,0,52,43],[85,0,41,88],[32,65,43,18]],"api_voice_id":[141,15,15,15],"api_voice_p_no":[1,0,0,0]},"api_friendly_battle":{"api_flare_pos":[-1,-1],"api_hougeki":{"api_at_eflag":[0,0,0,0],"api_at_list":[0,1,2,3],"api_n_mother_list":[0,0,0,0],"api_df_list":[[0],[2],[2],[0,0]],"api_si_list":[[190],[-1],[245],[280,280]],"api_cl_list":[[0],[1],[1],[1,1]],"api_sp_list":[0,0,0,1],"api_damage":[[0],[18],[59],[54,45]]}},"api_active_deck":[2,1],"api_touch_plane":["102",-1],"api_flare_pos":[-1,-1],"api_hougeki":{"api_at_eflag":[1,0,0,0,0],"api_at_list":[0,7,8,9,10],"api_n_mother_list":[0,0,0,0,0],"api_df_list":[[7],[0,0],[0,0],[0,0],[0,0]],"api_si_list":[[-1],["50","50"],["90","135"],["122","122"],["50","50"]],"api_cl_list":[[1],[1,1],[1,2],[1,1],[2,1]],"api_sp_list":[0,1,1,1,1],"api_damage":[[25],[47,24],[45,138],[10,11],[224,36]]}}}

**Comment by Nishisonic** [comment]
上の際のスクショとか
![vlcsnap-2018-02-17-13h02m38s765](https://user-images.githubusercontent.com/12210425/36337813-f5f62bc6-13e2-11e8-9069-01f67ed49779.png)
![vlcsnap-2018-02-17-13h02m50s575](https://user-images.githubusercontent.com/12210425/36337814-f7b360be-13e2-11e8-9b41-f015662b9036.png)
![vlcsnap-2018-02-17-13h03m14s462](https://user-images.githubusercontent.com/12210425/36337815-f8f93908-13e2-11e8-892c-1f7d0d4055fc.png)

**Comment by Nishisonic** [comment]
ミス
先程の戦闘分のスクショ
![vlcsnap-2018-02-17-13h06m44s631](https://user-images.githubusercontent.com/12210425/36337843-9eed7d7e-13e3-11e8-8aa3-521b17ad3b45.png)
![vlcsnap-2018-02-17-13h06m52s149](https://user-images.githubusercontent.com/12210425/36337844-a0002d7e-13e3-11e8-897c-2a920f654daf.png)
![vlcsnap-2018-02-17-13h07m29s546](https://user-images.githubusercontent.com/12210425/36337846-a1d03b58-13e3-11e8-8a1c-9252b0234fd5.png)
![vlcsnap-2018-02-17-13h07m33s177](https://user-images.githubusercontent.com/12210425/36337847-a3a857e4-13e3-11e8-81fa-e5ab5ab2546f.png)
![vlcsnap-2018-02-17-13h07m35s016](https://user-images.githubusercontent.com/12210425/36337849-a52fb60c-13e3-11e8-800f-186b55b36386.png)
![vlcsnap-2018-02-17-13h07m38s415](https://user-images.githubusercontent.com/12210425/36337850-a65eca54-13e3-11e8-8d20-c6fec98729e1.png)

**Comment by andanteyk** [comment]
ありがとうございます。頂いたデータをもとに修正しました。

**Comment by Nishisonic** [comment]
E-4甲 ボスマス 西村艦隊支援 json

{"api_result":1,"api_result_msg":"成功","api_data":{"api_deck_id":1,"api_formation":[14,14,3],"api_f_nowhps":[89,66,3,8,3,62],"api_f_maxhps":[89,90,65,66,68,62],"api_f_nowhps_combined":[53,49,48,37,37,49],"api_f_maxhps_combined":[53,64,64,41,37,49],"api_fParam":[[96,0,92,93],[98,0,84,94],[77,83,83,79],[77,82,82,79],[56,0,87,74],[55,0,86,75]],"api_fParam_combined":[[70,79,74,69],[77,84,106,78],[85,86,70,78],[59,99,59,59],[59,89,59,59],[63,139,49,63]],"api_ship_ke":[1785,1780,1558,1558,1529,1529],"api_ship_lv":[1,1,1,1,1,1],"api_ship_ke_combined":[1595,1595,1740,1740,1740,1740],"api_ship_lv_combined":[1,1,1,1,1,1],"api_e_nowhps":[201,0,0,0,0,0],"api_e_maxhps":[650,118,130,130,98,98],"api_e_nowhps_combined":[0,0,0,0,0,0],"api_e_maxhps_combined":[88,88,63,63,63,63],"api_eSlot":[[581,582,583,580,-1],[581,582,583,575,-1],[506,504,504,-1,-1],[506,504,504,-1,-1],[509,509,525,528,-1],[509,509,525,528,-1]],"api_eSlot_combined":[[505,505,515,525,-1],[505,505,515,525,-1],[501,501,559,-1,-1],[501,501,559,-1,-1],[501,501,559,-1,-1],[501,501,559,-1,-1]],"api_eParam":[[144,150,118,228],[48,0,68,93],[55,0,40,65],[55,0,40,65],[90,0,80,99],[90,0,80,99]],"api_eParam_combined":[[79,74,79,89],[79,74,79,89],[69,95,69,55],[69,95,69,55],[69,95,69,55],[69,95,69,55]],"api_friendly_info":{"api_production_type":1,"api_ship_id":[412,411,73,327,328,489,145],"api_ship_lv":[81,82,76,74,73,78,87],"api_nowhps":[36,37,38,15,16,22,28],"api_maxhps":[77,77,50,31,31,31,31],"api_Slot":[[7,7,272,101,-1],[7,7,88,74,-1],[50,50,15,26,-1],[266,15,88,-1,-1],[266,15,88,-1,-1],[266,15,88,-1,-1],[63,63,129,-1,-1]],"api_Param":[[86,0,72,79],[93,0,74,78],[61,58,53,59],[34,64,42,38],[36,55,43,35],[35,50,48,28],[30,69,58,41]],"api_voice_id":[141,141,141,141,141,141,141],"api_voice_p_no":[0,0,0,0,0,0,1]},"api_friendly_battle":{"api_flare_pos":[-1,-1],"api_hougeki":{"api_at_eflag":[0,1,0,0,0,0,0],"api_at_list":[0,0,2,3,4,5,6],"api_n_mother_list":[0,0,0,0,0,0,0],"api_df_list":[[0,0],[1],[0],[0,0],[0,-1,-1],[0,-1,-1],[0,0]],"api_si_list":[[7,7],[-1],[50],[266,15],[266,15,88],[266,15,88],[63,63]],"api_cl_list":[[1,1],[1],[0],[1,1],[1,-1,-1],[1,-1,-1],[1,1]],"api_sp_list":[1,0,0,2,7,7,1],"api_damage":[[32,56],[28],[0],[25,40],[33,-1,-1],[26,-1,-1],[25,28]]}},"api_active_deck":[2,1],"api_touch_plane":[-1,-1],"api_flare_pos":[-1,-1],"api_hougeki":{"api_at_eflag":[0,0,0],"api_at_list":[6,7,8],"api_n_mother_list":[0,0,0],"api_df_list":[[0,0],[0,0],[0,0]],"api_si_list":[["50","50"],["90","135"],["50","50"]],"api_cl_list":[[1,1],[1,1],[1,1]],"api_sp_list":[1,1,1],"api_damage":[[33,36],[39,56],[70,13]]}}}

**Comment by Nishisonic** [comment]
E-4甲 ボスマス 第19駆逐隊支援 json

{"api_result":1,"api_result_msg":"成功","api_data":{"api_deck_id":1,"api_formation":[14,14,1],"api_f_nowhps":[70,53,27,89,19,21],"api_f_maxhps":[105,97,90,89,62,68],"api_f_nowhps_combined":[22,61,64,41,49,37],"api_f_maxhps_combined":[53,64,64,41,49,37],"api_fParam":[[139,0,104,118],[138,0,93,116],[98,0,84,94],[96,0,92,93],[55,0,86,75],[56,0,87,74]],"api_fParam_combined":[[70,79,74,69],[77,84,106,78],[85,86,70,78],[59,99,59,59],[63,139,49,63],[59,89,59,59]],"api_ship_ke":[1788,1780,1558,1558,1567,1567],"api_ship_lv":[1,1,1,1,1,1],"api_ship_ke_combined":[1595,1595,1743,1743,1743,1743],"api_ship_lv_combined":[1,1,1,1,1,1],"api_e_nowhps":[240,0,0,0,0,15],"api_e_maxhps":[650,118,130,130,130,130],"api_e_nowhps_combined":[0,0,0,0,0,0],"api_e_maxhps_combined":[88,88,66,66,66,66],"api_eSlot":[[581,582,583,580,-1],[581,582,583,575,-1],[506,504,504,-1,-1],[506,504,504,-1,-1],[509,509,529,526,-1],[509,509,529,526,-1]],"api_eSlot_combined":[[505,505,515,525,-1],[505,505,515,525,-1],[501,501,570,-1,-1],[501,501,570,-1,-1],[501,501,570,-1,-1],[501,501,570,-1,-1]],"api_eParam":[[188,160,128,278],[48,0,68,93],[55,0,40,65],[55,0,40,65],[110,0,88,110],[110,0,88,110]],"api_eParam_combined":[[79,74,79,89],[79,74,79,89],[79,113,86,63],[79,113,86,63],[79,113,86,63],[79,113,86,63]],"api_friendly_info":{"api_production_type":2,"api_ship_id":[195,208,368,206],"api_ship_lv":[77,74,71,70],"api_nowhps":[32,30,30,30],"api_maxhps":[32,30,30,30],"api_Slot":[[63,63,74,-1,-1],[63,63,101,-1,-1],[2,125,28,-1,-1],[2,125,28,-1,-1]],"api_Param":[[53,49,28,28],[35,59,36,35],[23,58,27,34],[23,57,25,24]],"api_voice_id":[141,141,141,141],"api_voice_p_no":[1,2,0,0]},"api_friendly_battle":{"api_flare_pos":[1,-1],"api_hougeki":{"api_at_eflag":[0,1,0,1,0,0],"api_at_list":[0,0,1,5,2,3],"api_n_mother_list":[0,0,0,0,0,0],"api_df_list":[[11,11],[1],[0,0],[2,2],[5],[5,5]],"api_si_list":[[63,63],[-1],[63,63],[509,509],[2],[2,125]],"api_cl_list":[[1,1],[2],[1,1],[1,1],[1],[1,1]],"api_sp_list":[1,0,1,1,0,2],"api_damage":[[58,62],[18],[30,31],[3.1,2.1],[6],[31,5]]}},"api_active_deck":[2,1],"api_touch_plane":["102",-1],"api_flare_pos":[8,-1],"api_hougeki":{"api_at_eflag":[0,1,0,0,0,0,0],"api_at_list":[6,0,7,8,9,10,11],"api_n_mother_list":[0,0,0,0,0,0,0],"api_df_list":[[5,5],[10],[0,0],[0,0],[0,0],[0,0],[0,0]],"api_si_list":[["50","50"],[-1],["90","135"],["50","50"],["122","122"],["50","50"],["58","58"]],"api_cl_list":[[1,2],[0],[2,1],[1,1],[1,1],[1,1],[1,1]],"api_sp_list":[1,0,1,1,1,1,3],"api_damage":[[31,106],[0],[32,21],[11,13],[25,24],[35,9],[60,1]]}}}

**Comment by Nishisonic** [comment]
E-4甲 ボスマス 第四戦隊支援 json

{"api_result":1,"api_result_msg":"成功","api_data":{"api_deck_id":1,"api_formation":[14,14,1],"api_f_nowhps":[85,74,90,57,59,38],"api_f_maxhps":[99,90,90,66,68,62],"api_f_nowhps_combined":[14,53,55,41,51,29],"api_f_maxhps_combined":[48,53,64,41,63,37],"api_fParam":[[145,0,86,118],[98,0,84,94],[106,0,98,93],[77,82,82,79],[56,0,87,74],[55,0,86,75]],"api_fParam_combined":[[36,0,48,19],[70,79,74,69],[84,84,72,77],[59,99,59,59],[80,88,80,78],[59,89,59,59]],"api_ship_ke":[1529,1529,1529,1524,1524,1524],"api_ship_lv":[1,1,1,1,1,1],"api_ship_ke_combined":[1555,1592,1577,1577,1501,1501],"api_ship_lv_combined":[1,1,1,1,1,1],"api_e_nowhps":[98,98,98,90,90,90],"api_e_maxhps":[98,98,98,90,90,90],"api_e_nowhps_combined":[57,66,38,38,20,20],"api_e_maxhps_combined":[57,66,38,38,20,20],"api_eSlot":[[509,509,525,528,-1],[509,509,525,528,-1],[509,509,525,528,-1],[509,509,512,528,-1],[509,509,512,528,-1],[509,509,512,528,-1]],"api_eSlot_combined":[[506,525,542,543,-1],[550,550,545,525,-1],[502,515,542,-1,-1],[502,515,542,-1,-1],[501,-1,-1,-1,-1],[501,-1,-1,-1,-1]],"api_eParam":[[90,0,80,99],[90,0,80,99],[90,0,80,99],[85,0,70,85],[85,0,70,85],[85,0,70,85]],"api_eParam_combined":[[48,80,30,39],[64,92,96,68],[44,72,36,29],[44,72,36,29],[5,15,6,5],[5,15,6,5]],"api_midnight_flag":0,"api_search":[1,1],"api_air_base_attack":[{"api_base_id":1,"api_stage_flag":[1,1,1],"api_plane_from":[null,[1,2,3,7,8]],"api_squadron_plane":[{"api_mst_id":170,"api_count":18},{"api_mst_id":180,"api_count":18},{"api_mst_id":186,"api_count":18},{"api_mst_id":186,"api_count":18}],"api_stage1":{"api_f_count":72,"api_f_lostcount":0,"api_e_count":20,"api_e_lostcount":7,"api_disp_seiku":1,"api_touch_plane":[-1,-1]},"api_stage2":{"api_f_count":72,"api_f_lostcount":4,"api_e_count":0,"api_e_lostcount":0},"api_stage3":{"api_erai_flag":[1,0,0,1,0,1],"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,1,0,0],"api_edam":[32,0,0,140.1,0,30]},"api_stage3_combined":{"api_erai_flag":[0,0,0,0,0,1],"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,0,0,141]}},{"api_base_id":1,"api_stage_flag":[1,1,1],"api_plane_from":[null,[1,2,3,7,8]],"api_squadron_plane":[{"api_mst_id":170,"api_count":18},{"api_mst_id":180,"api_count":18},{"api_mst_id":186,"api_count":18},{"api_mst_id":186,"api_count":18}],"api_stage1":{"api_f_count":72,"api_f_lostcount":0,"api_e_count":13,"api_e_lostcount":1,"api_disp_seiku":1,"api_touch_plane":[-1,-1]},"api_stage2":{"api_f_count":72,"api_f_lostcount":4,"api_e_count":0,"api_e_lostcount":0},"api_stage3":{"api_erai_flag":[1,0,0,0,0,0],"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[30,0,0,0,0,0]},"api_stage3_combined":{"api_erai_flag":[0,1,0,1,0,0],"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,1,0,0],"api_edam":[0,59,0,323,0,0]}},{"api_base_id":2,"api_stage_flag":[1,1,1],"api_plane_from":[null,[1,2,3,7,8]],"api_squadron_plane":[{"api_mst_id":180,"api_count":18},{"api_mst_id":187,"api_count":18},{"api_mst_id":169,"api_count":18},{"api_mst_id":169,"api_count":18}],"api_stage1":{"api_f_count":72,"api_f_lostcount":0,"api_e_count":12,"api_e_lostcount":2,"api_disp_seiku":1,"api_touch_plane":[-1,-1]},"api_stage2":{"api_f_count":72,"api_f_lostcount":12,"api_e_count":0,"api_e_lostcount":0},"api_stage3":{"api_erai_flag":[0,0,1,0,0,1],"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,0,0,61]},"api_stage3_combined":{"api_erai_flag":[1,0,0,0,0,0],"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[178,0,0,0,0,0]}},{"api_base_id":2,"api_stage_flag":[1,1,1],"api_plane_from":[null,[1,2,3,8]],"api_squadron_plane":[{"api_mst_id":180,"api_count":18},{"api_mst_id":187,"api_count":18},{"api_mst_id":169,"api_count":18},{"api_mst_id":169,"api_count":18}],"api_stage1":{"api_f_count":72,"api_f_lostcount":0,"api_e_count":9,"api_e_lostcount":4,"api_disp_seiku":1,"api_touch_plane":[-1,-1]},"api_stage2":{"api_f_count":72,"api_f_lostcount":6,"api_e_count":0,"api_e_lostcount":0},"api_stage3":{"api_erai_flag":[0,1,1,0,0,0],"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,83,23,0,0,0]},"api_stage3_combined":{"api_erai_flag":[0,0,1,0,1,0],"api_ebak_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_edam":[0,0,0,0,135,0]}}],"api_stage_flag":[1,1,1],"api_kouku":{"api_plane_from":[[4,5,6,7],null],"api_stage1":{"api_f_count":97,"api_f_lostcount":0,"api_e_count":0,"api_e_lostcount":0,"api_disp_seiku":1,"api_touch_plane":[239,-1]},"api_stage2":{"api_f_count":9,"api_f_lostcount":4,"api_e_count":0,"api_e_lostcount":0},"api_stage3":{"api_frai_flag":[0,0,0,0,0,0],"api_erai_flag":[0,0,1,0,0,0],"api_fbak_flag":[0,0,0,0,0,0],"api_ebak_flag":[0,0,0,0,0,0],"api_fcl_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_fdam":[0,0,0,0,0,0],"api_edam":[0,0,9,0,0,0]},"api_stage3_combined":{"api_frai_flag":[0,0,0,0,0,0],"api_erai_flag":[0,0,1,0,0,0],"api_fbak_flag":[0,0,0,0,0,0],"api_ebak_flag":[0,0,0,0,0,0],"api_fcl_flag":[0,0,0,0,0,0],"api_ecl_flag":[0,0,0,0,0,0],"api_fdam":[0,0,0,0,0,0],"api_edam":[0,0,0,0,0,0]}},"api_support_flag":2,"api_support_info":{"api_support_airatack":null,"api_support_hourai":{"api_deck_id":3,"api_ship_id":[116,8909,9309,2569,15778,67838],"api_undressing_flag":[0,0,0,0,0,0],"api_cl_list":[1,0,0,0,2,0,0,0,0,0,0,0],"api_damage":[72,0,0,0,241.1,0,0,0,0,0,0,0]}},"api_opening_taisen_flag":0,"api_opening_taisen":null,"api_opening_flag":0,"api_opening_atack":null,"api_hourai_flag":[1,1,0,0],"api_hougeki1":{"api_at_eflag":[0,0],"api_at_list":[0,2],"api_at_type":[6,6],"api_df_list":[[1],[2]],"api_si_list":[["239","128","128"],["118","161","161"]],"api_cl_list":[[1],[1]],"api_damage":[[266],[201]]},"api_hougeki2":{"api_at_eflag":[0,0],"api_at_list":[0,1],"api_at_type":[6,2],"api_df_list":[[8],[7,7]],"api_si_list":[["239","128","128"],["105","103"]],"api_cl_list":[[1],[1,1]],"api_damage":[[294],[176,170]]}}}

**Comment by Nishisonic** [comment]
E-4甲 ボスマス 挺身部隊支援 json

{"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_deck_id":1,"api_formation":[14,14,1],"api_f_nowhps":[57,43,80,29,82,29],"api_f_maxhps":[57,99,91,81,82,68],"api_f_nowhps_combined":[45,43,7,43,57,61],"api_f_maxhps_combined":[45,43,37,43,57,69],"api_fParam":[[85,86,70,78],[141,0,105,125],[118,0,100,110],[96,0,92,93],[98,0,84,94],[56,0,87,74]],"api_fParam_combined":[[68,79,72,69],[59,99,59,59],[59,89,59,59],[63,139,49,63],[77,84,106,78],[55,0,86,75]],"api_ship_ke":[1784,1558,1558,1558,1529,1529],"api_ship_lv":[1,1,1,1,1,1],"api_ship_ke_combined":[1594,1594,1576,1576,1501,1501],"api_ship_lv_combined":[1,1,1,1,1,1],"api_e_nowhps":[193,0,0,0,0,0],"api_e_maxhps":[650,130,130,130,98,98],"api_e_nowhps_combined":[0,0,0,0,0,0],"api_e_maxhps_combined":[80,80,37,37,20,20],"api_eSlot":[[581,582,583,580,-1],[506,504,504,-1,-1],[506,504,504,-1,-1],[506,504,504,-1,-1],[509,509,525,528,-1],[509,509,525,528,-1]],"api_eSlot_combined":[[505,505,515,525,-1],[505,505,515,525,-1],[502,545,542,-1,-1],[502,545,542,-1,-1],[501,-1,-1,-1,-1],[501,-1,-1,-1,-1]],"api_eParam":[[124,130,108,198],[55,0,40,65],[55,0,40,65],[55,0,40,65],[90,0,80,99],[90,0,80,99]],"api_eParam_combined":[[73,66,72,82],[73,66,72,82],[38,66,32,26],[38,66,32,26],[5,15,6,5],[5,15,6,5]],"api_escape_idx_combined":[2,3],"api_friendly_info":{"api_production_type":2,"api_ship_id":[150,152,144,323,228,316],"api_ship_lv":[84,84,74,65,75,71],"api_nowhps":[83,82,31,30,32,34],"api_maxhps":[83,82,31,30,32,34],"api_Slot":[[7,7,88,74,-1],[7,7,35,88,-1],[63,63,15,-1,-1],[63,63,15,-1,-1],[266,266,15,-1,-1],[266,266,15,-1,-1]],"api_Param":[[84,0,66,88],[87,0,48,78],[34,54,42,37],[32,55,24,33],[27,65,43,42],[34,62,46,41]],"api_voice_id":[141,141,141,141,141,141],"api_voice_p_no":[1,2,0,0,0,0]},"api_friendly_battle":{"api_flare_pos":[-1,-1],"api_hougeki":{"api_at_eflag":[0,1,0,0,0,0,0],"api_at_list":[0,0,1,2,3,4,5],"api_n_mother_list":[0,0,0,0,0,0,0],"api_df_list":[[0,0],[2],[0,0],[0,0],[0],[0,0],[0,0]],"api_si_list":[[7,7],[-1],[7,7],[63,15],[63],[266,15],[266,15]],"api_cl_list":[[1,1],[0],[1,1],[1,1],[1],[1,1],[1,1]],"api_sp_list":[1,0,1,2,0,2,2],"api_damage":[[55,39],[0],[62,48],[51,31],[23],[21,15],[27,26]]}},"api_active_deck":[2,1],"api_touch_plane":[-1,-1],"api_flare_pos":[-1,-1],"api_hougeki":{"api_at_eflag":[0,0],"api_at_list":[6,9],"api_n_mother_list":[0,0],"api_df_list":[[0,0],[0,0]],"api_si_list":[["50","65"],["65","134"]],"api_cl_list":[[2,1],[1,1]],"api_sp_list":[1,1],"api_damage":[[104,23],[17,62]]}}}

**Comment by hkuno9000** [comment]
api_flare_pos の艦インデックス番号は 1 ベースでしたが、今回のイベントから 0 ベースに変わったとの報告あり
現在、調査中。

https://github.com/hkuno9000/KanColle-YPS/pull/116

**Comment by Nishisonic** [comment]
武蔵改二専用?対空CI26種の情報について
https://twitter.com/galpokopii/status/964584564294279168
https://twitter.com/galpokopii/status/964588515546681344
https://twitter.com/galpokopii/status/964612805461594113

**Comment by leeyc0** [comment]
E-3 boss night battle throws index out of bound exception

```
エラーレポート [ver. 3.0.7] : 2018/02/24 14:24:53
エラー : ArgumentOutOfRangeException
索引超出範圍。必須為非負數且小於集合的大小。
參數名稱: index
追加情報 : Responseの受信中にエラーが発生しました。
スタックトレース：
   於 System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   於 System.SZArrayHelper.get_Item[T](Int32 index)
   於 ElectronicObserver.Window.FormBattle.SetNightBattleEvent(PhaseNightBattle pd)
   於 ElectronicObserver.Window.FormBattle.Updated(String apiname, Object data)
   於 ElectronicObserver.Observer.APIReceivedEventHandler.Invoke(String apiname, Object data)
   於 CallSite.Target(Closure , CallSite , APIReceivedEventHandler , String , Object )
   於 ElectronicObserver.Observer.APIBase.OnResponseReceived(Object data)
   於 ElectronicObserver.Observer.kcsapi.api_req_combined_battle.ec_midnight_battle.OnResponseReceived(Object data)
   於 CallSite.Target(Closure , CallSite , APIBase , Object )
   於 System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid2[T0,T1](CallSite site, T0 arg0, T1 arg1)
   於 CallSite.Target(Closure , CallSite , APIBase , Object )
   於 ElectronicObserver.Observer.APIDictionary.OnResponseReceived(String apiname, Object data)
   於 CallSite.Target(Closure , CallSite , APIDictionary , String , Object )
   於 ElectronicObserver.Observer.APIObserver.LoadResponse(String path, String data)

通信内容 : api_req_combined_battle/ec_midnight_battle
svdata={"api_result":1,"api_result_msg":"\u6210\u529f","api_data":{"api_deck_id":1,"api_formation":[14,14,2],"api_f_nowhps":[74,17,73,28,58,26],"api_f_maxhps":[85,85,86,87,58,58],"api_f_nowhps_combined":[14,22,34,25,17,39],"api_f_maxhps_combined":[46,37,37,53,52,43],"api_fParam":[[86,0,92,92],[86,0,92,92],[70,0,88,83],[65,0,90,84],[34,0,72,65],[34,0,72,65]],"api_fParam_combined":[[59,91,83,69],[60,54,110,54],[57,54,116,53],[77,75,64,72],[78,77,65,72],[63,139,49,63]],"api_ship_ke":[1782,1615,1615,1543,1595,1595],"api_ship_lv":[1,1,1,1,1,1],"api_ship_ke_combined":[1555,1592,1577,1577,1577,1577],"api_ship_lv_combined":[1,1,1,1,1,1],"api_e_nowhps":[243,0,0,0,0,0],"api_e_maxhps":[350,96,96,90,88,88],"api_e_nowhps_combined":[0,0,0,0,0,0],"api_e_maxhps_combined":[57,66,38,38,38,38],"api_eSlot":[[581,557,558,583,-1],[556,557,558,558,-1],[556,557,558,558,-1],[509,509,525,529,-1],[505,505,515,525,-1],[505,505,515,525,-1]],"api_eSlot_combined":[[506,525,542,543,-1],[550,550,545,525,-1],[502,515,542,-1,-1],[502,515,542,-1,-1],[502,515,542,-1,-1],[502,515,542,-1,-1]],"api_eParam":[[198,0,160,220],[25,0,50,80],[25,0,50,80],[85,0,70,96],[79,74,79,89],[79,74,79,89]],"api_eParam_combined":[[48,80,30,39],[64,92,96,68],[44,72,36,29],[44,72,36,29],[44,72,36,29],[44,72,36,29]],"api_active_deck":[2,1],"api_touch_plane":["102",-1],"api_flare_pos":[10,-1],"api_hougeki":{"api_at_eflag":[0,1,0,0,0,0],"api_at_list":[6,0,8,9,10,11],"api_n_mother_list":[0,0,0,0,0,0],"api_df_list":[[0,0],[7],[0,0],[0,0],[0,0],[0,0]],"api_si_list":[["139","139"],[-1],["122","122"],["50","50"],["50","50"],["134","134"]],"api_cl_list":[[1,2],[1],[1,1],[1,1],[1,1],[1,1]],"api_sp_list":[1,0,1,1,1,1],"api_damage":[[26,21],[17],[23,13],[22,8],[13,13],[107,84]]}}}
```

**Comment by RadarNyan** [comment]
照明弾インデックスに関する暫定修正：

```diff
@@ -203,11 +203,11 @@ namespace ElectronicObserver.Data.Battle.Phase
 		public int FlareIndexFriend
 		{
 			get
 			{
 				int index = (int)RawData.api_flare_pos[0];
-				return index != -1 ? index - 1 : -1;
+				return index > 5 ? index - 6 : index;
 			}
 		}
 
 		/// <summary>
 		/// 敵軍照明弾投射艦番号(0-5, -1=発動せず)
@@ -215,11 +215,11 @@ namespace ElectronicObserver.Data.Battle.Phase
 		public int FlareIndexEnemy
 		{
 			get
 			{
 				int index = (int)RawData.api_flare_pos[1];
-				return index != -1 ? index - 1 : -1;
+				return index > 5 ? index - 6 : index;
 			}
 		}
```

1 ベースから 0 ベースになただけじゃない、連合艦隊（随伴艦隊）の場合、6 ベースになています。

**Comment by andanteyk** [comment]
@RadarNyan  ありがとうございます、こちらでも確認できました。修正しました。
