### ISSUE TITLE
基地航空隊：補給/疲労アイコンの表示優先度について

### ISSUE THREAD

**Issue by andanteyk** [andanteyk/ElectronicObserver#207]
機数調整をしていると疲労が確認できないので優先度を変えてほしい、とのこと
検討中

**Comment by CNA-Bld** [comment]
+1
IMO 疲労 should be prioritized over 補給.
~~そもそもなぜ基地航空隊が疲労するか~~

**Comment by andanteyk** [comment]
aa8bb4bb5ccd1a265a41860e3214b72a335189f8　で実装。
