### ISSUE TITLE
remodel_slotlist_detail doc update

### ISSUE THREAD

**Issue by gakada** [andanteyk/ElectronicObserver#210]
In addition to

https://github.com/andanteyk/ElectronicObserver/blob/a6bf856023796ad744906237889f0e7a304173a6/ElectronicObserver/Other/Information/apilist.txt#L764-L765

there is also `api_req_useitem_id2` and `api_req_useitem_num2` for when two items are used (like 12.7cm連装砲C型改二 -> 12.7cm連装砲D型改二).

**Comment by gakada** [comment]
Also something unrelated, but maybe it can be mentioned in kcmemo. Wikiwiki [states](http://wikiwiki.jp/kancolle/?%B6%E1%C2%E5%B2%BD%B2%FE%BD%A4#ha8aa858) that successful modernization bonus is floor(n + (n + 1) / 5), which is also defined in scene.remodel.view.powup.PowupUI in RemodelMain as floor(n * 1.2 + 0.3) (same function).

**Comment by andanteyk** [comment]
Thank you for your information.
Updated at aa8bb4bb5ccd1a265a41860e3214b72a335189f8 .
