### ISSUE TITLE
1.2.0 任務統計bug

### ISSUE THREAD

**Issue by hoshinokana** [andanteyk/ElectronicObserver#23]
今日(2015-04-28) 5時 任務更新　見つかりました。
前の日 未完の任務　消えるはありません。
日本語が得意ではありません。理解することを望んでいます。 ('_')
![20150428043242](https://cloud.githubusercontent.com/assets/12150066/7366549/c340098a-edcb-11e4-845f-ff216e69f3be.jpg)

**Comment by REIS252** [comment]
任務を受けてその日のうちにクリア出来ずに翌日に再度受けると
前日のカウントが残ったままになってしまう不具合だと当方もなります
デイリー任務で再現するかと思います

**Comment by RJHsiao** [comment]
まぁ、海外（日本国以外）の提督さんですよね～
僕は台湾の提督ですから、このバグも遭遇しました
このバグの発生原因は、多分パソコンに設定された所属地域（タイムゾーン）に関連すると、僕はそう思います

七四式電子観測儀の任務リストの更新時間は、多分艦これのサーバーと同じく、 "Local Time” の５時に設定されたと思います。
でも、例えば台湾（UTC + 8）の場合は、日本標準時（UTC + 9）の５時＝台湾の４時です、所属地域は台湾に設定されたパソコンの "Local Time” はまだ４時です。七四式電子観測儀はまだ更新の時間じゃないと判断し、だから任務リストを更新しない。
僕はこれはそのバグの発生原因だと思います。

僕も日本語の書き方は上手くではないですから、ご理解すると幸いです。

**Comment by andanteyk** [comment]
ご報告ありがとうございます。その可能性は十分考えられると思います。
イベント関連の更新が終わり次第になるので時間がかかってしまうかもしれませんが、確認します。

**Comment by RJHsiao** [comment]
:+1::+1::+1:

一応こちから修正し、PRしたいですけと（こちから確認しやすいですから）
でも全然始まらないですね．．．お恥ずかしいです　:sweat:

**Comment by andanteyk** [comment]
111a686f8a7b51de998e9c4157573440930f5e9d で修正版をマージしました。
次回更新で適用します。
