### ISSUE TITLE
カラープロファイルの問題？

### ISSUE THREAD

**Issue by andanteyk** [andanteyk/ElectronicObserver#238]
http://electronicobserver.blog.fc2.com/blog-entry-103.html#comment3391
色が変わって見えるらしい？

**Comment by silfumus** [comment]
Probably related: [Chrome displaying colours incorrectly](https://productforums.google.com/forum/#!topic/chrome/DtdkQfD1aSA) and https://warosu.org/jp/thread/S19753386#p19757970

**Comment by veigr** [comment]
Chrome/Chromium は標準でカラーマネジメントが働きますので、IE/Trident とは異なる色味になります。

参考:  [続・Webブラウザのカラーマネジメント対応まとめ : やんま まのblog（仮）](http://blog.livedoor.jp/yamma_ma/archives/38413741.html)
(ハードウェアアクセラレーション有効/無効の場合の変化についてもコメントに記載があります)

正しく設定されている場合は、Chrome/Chromium の方がむしろ正しい色と言えるでしょう。

Chrome/Chromium の最近のバージョンにはマルチモニタ時にモニタプロファイルをプライマリモニタ以外から取得してしまうバグがあったようですが、ちょっと前に修正されたような記憶が……
CefSharpが採用しているバージョンがどうかは詳しく調べないとわからないですね。
