### ISSUE TITLE
faster game extraction location

### ISSUE THREAD

**Issue by aiqinxuancai** [andanteyk/ElectronicObserver#241]
I tested using this code very stable

`        
private void Browser_FrameLoadEnd(object sender, FrameLoadEndEventArgs e)
        {
            if (e.Frame.Name == "game_frame")
            {
                BeginInvoke((Action)(() =>
                {
                    ApplyStyleSheet();
                }));
            }
        }
`

**Comment by RadarNyan** [comment]
When ```FrameLoadEnd``` is called, the page is **NOT necessary finished** loading (DOM might not be ready yet) so with the current javascript it might be unstable for higher latency network.

The solution I came up with was to change the script to listen to event if DOM not available, see:
https://github.com/RadarNyan/CefEOBrowser/commit/ab92b6d3274d18c9b22f9fb5dbb6ccc201c603a3
