### ISSUE TITLE
Capturing may cause memory leak

### ISSUE THREAD

**Issue by xiaozhikang0916** [andanteyk/ElectronicObserver#243]
Found that each screen capturing action will rise the memory usage of 74EO, likely 10mb per action at average, not precisely, and leaving some `ss_UUID` object in global-varable pool of js.

It may need some delete or unregister action to release these memory

![image](https://user-images.githubusercontent.com/8273026/44956321-9af80980-aef4-11e8-8bd9-877cff0cd161.png)

**Comment by xiaozhikang0916** [comment]
After capturing done, hit Pause button in DevTools->Sources tab at any time you like, then you can check the alive objects in the `Scope`, and the `ss-UUID` objects are stored in `global`

![image](https://user-images.githubusercontent.com/8273026/45157344-7f05a800-b213-11e8-92ac-b4f3ba292a15.png)

**Comment by andanteyk** [comment]
情報ありがとうございます。

こちらでも `ss_UUID` が残っているのを確認できました。
CefSharp 側のコードを読んだところ、 `Browser.JavascriptObjectRepository.UnRegister()` は .NET 側のオブジェクトは削除するものの、 js 側には何もしないように見えます。

そのため、 fb3aa83d652e93f215fde00ffda23baad89e8c80 で、`ss_UUID` を削除する js を呼び出すコードを追加しました。
今のところ削除処理は成功しており、問題なく動作しています。

ただ、私は CefSharp 側の処理を把握できていないため、これが正しいかは分かりません。
もし問題があれば教えてください。

**Comment by xiaozhikang0916** [comment]
It looks good in reviewing, except some tiny points

A `ToString` call without assignment? [Link to code](https://github.com/andanteyk/ElectronicObserver/blob/fb3aa83d652e93f215fde00ffda23baad89e8c80/Browser/FormBrowser.cs#L616)

It looks like the capturing feature calling stack is full of `async` and `await`, can it be done in a single `await` call, leaving other methods executed sequentially? I'm not that familiar with C# coding with async-and-await so I'm not sure the execution order, e.g. will `delete {result.ID}` executed before `dataurl = canvas.toDataURL('image/png')` in JS? But since it works fine now, it may need no more modification.

Found that you [left a comment](https://github.com/andanteyk/ElectronicObserver/blob/fb3aa83d652e93f215fde00ffda23baad89e8c80/Browser/FormBrowser.cs#L656) in the code and still not sure of setting `preserveDrawingBuffer`. You can check my latest comment in #234 if you missed.

**Comment by andanteyk** [comment]
> ToString

デバッグ用のコードを消し忘れました…　ご指摘ありがとうございます。

> async/await

一応、現在のコードでも `{request.ID}.complete()` → `delete` になることは await によって保証されているはずです。
もちろん、もっとうまくやる方法はあると思います。

> Found that you left a comment

確認はしていました。情報ありがとうございました。
消し忘れたコメント・コードを削除しました。
