### ISSUE TITLE
Chromium 64ビットカーネルを削除することができます

### ISSUE THREAD

**Issue by fei5seven** [andanteyk/ElectronicObserver#244]
申し訳ありません、私はマシンを使用することができます。
chromium32ビットカーネルは64ビットウィンドウで使用できますが、74では64ビットカーネルを使用しません。圧縮パッケージのファイルサイズを減らすために、それを削除することを検討してください。

**Comment by andanteyk** [comment]
次のバージョンから、64bit 環境では 64bit で動作するようになる予定です。
