### ISSUE TITLE
about quest requirement

### ISSUE THREAD

**Issue by zhailingzy** [andanteyk/ElectronicObserver#245]
is it possible to load quest setting from xml or config file  rather than hard coded in program?

**Comment by andanteyk** [comment]
「任務の達成条件を外部ファイルから読み込む」機能のことだと推測します。

私はそれが必要だとは思いません。
その機能が必要だと考えた理由はありますか？実現することでどんな利点がありますか？

**Comment by zhailingzy** [comment]
Maybe I should fork and develop it for myself, for my own issue I just want to record the progress of some onetime quest.
Thanks.
