### ISSUE TITLE
ブラウザ：長い艦名、装備名が表示領域の外にあふれる不具合

### ISSUE THREAD

**Issue by kuromak** [andanteyk/ElectronicObserver#269]
下記画像のような感じで、海外艦などの長い艦名、装備が隣の画像「改修maxアイコン」や「艦娘画像」等にぶつかるまではみ出して表示されます。
発生する画面は「編成画面（艦娘名・装備両方、リスト・詳細両方）」「演習相手の艦娘名」「入渠画面の艦娘名」で確認できております。同じタイプの他の画面（リスト・対象をクリックして右からカードが出てくるタイプの画面）で発生するのではと思っております。
Commandan Teste改や L.d.S.D.d.Abruzzi改のように文字数が多く長くなりがちな艦娘で確認がしやすいと思います。

改装画面ではこの事象は発生しませんし、通常のChromeブラウザで表示している場合は再現しません。
また、スタイルシートの適用のチェックを外した状態での動作でもこの現象は再現します。
内蔵されているブラウザの仕様の問題かもしれませんが確認と可能であれば対応をお願いいたします。

![image](https://user-images.githubusercontent.com/50373899/82177079-80a5cf80-9913-11ea-96b8-224369bf7a8b.png)

**Comment by andanteyk** [comment]
![image](https://user-images.githubusercontent.com/4958081/82207769-53721500-9945-11ea-8517-0c6d3b0ee3d8.png)

再現できませんでした。
内蔵ブラウザの編成画面・入渠画面で、ズーム有り無し両方について確認しました。

・最新版をご利用しょうか。
　4.5.0 でブラウザの更新を行ったため、それ以前のバージョンで発生する可能性はなくはないです。
　（一応 4.4.1 で確認しましたが、きちんと描画されていたので関係はないかもしれません。）
・ダメもとでキャッシュをクリアしてみるとよいかもしれません。
　本ツールを終了してから BrowserCache フォルダを削除してみてください。

最も、内蔵ブラウザの描画システムについてはほぼこちらで関与していないため、私ができることは内蔵ブラウザの更新ぐらいしかないです。（現状ほぼ最新版のはずですが…）
一応 Chrome 79.0 (っぽいもの) が入っています。

> "Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36"

**Comment by myangelkamikaze** [comment]
I can reproduce this in 2 different ways:

1. disable hardware acceleration
2. run 74EO in compatibility mode for Windows Vista, this would probably happen when using an older OS

**Comment by kuromak** [comment]
> ・最新版をご利用しょうか。
　4.5.0 でブラウザの更新を行ったため、それ以前のバージョンで発生する可能性はなくはないです。
　（一応 4.4.1 で確認しましたが、きちんと描画されていたので関係はないかもしれません。）
・ダメもとでキャッシュをクリアしてみるとよいかもしれません。
　本ツールを終了してから BrowserCache フォルダを削除してみてください。

こちら、4.5.1で確認しております。
ですが、今まで #242 への対策として、「ハードウェアアクセラレーションを有効」のチェックを今まで念のため外していたのですが、これを有効にしたところ表示が正しくなりました。

また、通常のChrome（Windows 64ビット版）
> Google Chrome は最新版です
バージョン: 81.0.4044.138（Official Build） （64 ビット）

でハードウェアアクセラレーションをOFFにしても再現したので、ハードウェアアクセラレーションをオフにすることで発生する仕様だったようです。
調査不足申し訳ありませんでした。
