### ISSUE TITLE
七四式電子探信儀 ゴーストウィンドウ

### ISSUE THREAD

**Issue by zubo334** [andanteyk/ElectronicObserver#270]
![image](https://user-images.githubusercontent.com/66857034/84558133-75578f80-ad6b-11ea-92bc-796b12d7c2ae.png)

メインウィンドウのほかにCtrl+Tab画面にのみ現れるゴーストウィンドウが発生しています。
緊急性は低いですが面倒なバグです。

**Comment by Tsukumoyarei** [comment]
Browser/FormBrowser.csに
`protected override CreateParams CreateParams
		{
			get
			{
				CreateParams cp = base.CreateParams;
				cp.ExStyle |= 0x80;
				return cp;
			}
		}`
そしてコンストラクタに
`this.ShowInTaskbar = false;`
を追加するとゴーストウィンドウが消失します。
なお、Alt+Tabからのウィンドウがなくなりますので、そこでブラウザのウィンドウを（ミスで）閉じれる不具合もfixされます。
参考：(http://www.csharp411.com/hide-form-from-alttab/)

**Comment by andanteyk** [comment]
ver. 4.6.5 で対応した…はずです。  
再発していた場合は、再オープンするかブログのコメントに残してください。
