### ISSUE TITLE
メニューバーのあるウィンドウをドッキングするとメニューが使えなくなるetc.

### ISSUE THREAD

**Issue by HrhtAtKanColleInKanoya** [andanteyk/ElectronicObserver#290]
メニューバーのあるウィンドウをドッキングするとメニューが使えなくなります。
他に、テキストボックス系パーツの入力を受け付けなくなるウィンドウが（すべてのウィンドウではなく）あります
があります。
仕様なのか機能制限なのか不具合なのか、お時間あるときで構いませんので調査お願いできますでしょうか

**Comment by andanteyk** [comment]
ウィンドウキャプチャのことでしょうか？

ヘルプに記述した通り、個別のウィンドウの動作については対応することができません。  
(この機能の調整にさける気力がもはや残っていません。
お待たせしたうえこのような回答になり大変申し訳ありませんが、ドッキングせず扱うなどして回避してください。)

> ウィンドウによっては取り込めない・誤動作を引き起こす可能性があります。
個別には対応できませんのでご了承ください。
