### ISSUE TITLE
要望:艦船グループでの表示内容について

### ISSUE THREAD

**Issue by Azumina373** [andanteyk/ElectronicObserver#291]
今回の2021春イベで札管理のために全艦船をCSV出力することがあったのですが、同型艦でソートができないので管理がしにくいということがありました。
なのでゲーム内の艦種順表示位置を表示できるようにしていただきたいです。

**Comment by andanteyk** [comment]
艦これ本体側の母港のソート順と同じにできればよい、の認識で合っていますか？  
（艦型・n番艦の情報ではなく）  

37b820f6bdea25566d50af64bd00e1cea1581383 で「母港ソートID」列を追加しました。  
これをキーにしてソートすればおそらく本体の編成リストと同じ並び順になるはずです。
（同じ艦が重複した場合の処理はすみませんが失念したので、Exp か何かをサブキーにするとよいです）

もし勘違い等あれば再オープンするか、ブログのコメントに残してください。
