### ISSUE TITLE
Kancolle-db Support

### ISSUE THREAD

**Issue by hyspace** [andanteyk/ElectronicObserver#38]
I use kancolle-db.net a lot, and I want to contribute to its data collection. Can you add an option to support kancolle-db data collection?

If you are not familiar with it, this is the link:

Website:
http://kancolle-db.net/

Post sample:
https://github.com/about518/kanColleDbPost

@about518 maybe you can help with this?

**Comment by hyspace** [comment]
1.3.0 has already added this option.

**Comment by andanteyk** [comment]
At 2ebb2ee43ee09d673f91ccb35b240fae3c770b56, sending function of KanColle Database has been implemented.
It will be available in the next update.
