### ISSUE TITLE
艦船図鑑⑤を選択すると実行時エラーとなる

### ISSUE THREAD

**Issue by vanishcrow** [andanteyk/ElectronicObserver#43]
2015/5/29のアップデートで艦船図鑑⑤が追加されましたが、これをクリックすると以下のメッセージが飛んできます。
```
{"api_result":1,"api_result_msg":"成功","api_data":null}
```
ShipParameterRecord.AlbumOpened()やFormInformation.GetAlbumInfo()はapi_dataに値が入っていることが前提の処理となっているため、null参照でエラーとなってしまいます。
（プレイには影響ありませんが）

ちょっと影響範囲が広そうなのでIssueに登録だけしておきます。

**Comment by andanteyk** [comment]
ご報告ありがとうございます。
93953b61ad1a9fae6dd05aa820a4acbe8d7065f1 で修正しました。
