### ISSUE TITLE
艦これ統計データベースへの送信におけるAPIフィルタについて

### ISSUE THREAD

**Issue by nekopanda** [andanteyk/ElectronicObserver#47]
艦これ統計データベースへの送信で、送るAPIをフィルタする機能がありますが、一部のAPIしか送らないというのはサーバ側での処理に支障を来す恐れがあると思います。艦これDBの作者様に直接聞いたわけではありませんが、たいていの専ブラやツールは一部のAPIしか受け取れない状況ではうまく動かないと思うので、危険ではないかと。

もし、艦これDBの作者様からOKを頂いているということでしたら、私の杞憂ですので無視してください。

**Comment by andanteyk** [comment]
そこまで考えが至りませんでした、ご指摘ありがとうございます。
問い合わせてみます。

**Comment by andanteyk** [comment]
問い合わせたところ「すべて送っていただきたい」とのことでしたので、 55a767eca13b4465145ff34bb56cf974e2841d85 にて当該機能を削除しました。
また、仕様変更で不要になったAPIを送信しないよう b09220a87a5d9accd5a0f023c069247fa4821441 にて対応しました。

繰り返しになりますが、ご指摘ありがとうございました。
