### ISSUE TITLE
演習のS勝利の獲得経験値予測が1多いことがある

### ISSUE THREAD

**Issue by fujieda** [andanteyk/ElectronicObserver#50]
情報ウィンドウの演習の獲得経験値予測で、S勝利の場合が実際より1多いことがあります。[ここの計算](https://github.com/andanteyk/ElectronicObserver/blob/master/ElectronicObserver/Window/FormInformation.cs#L120)は、`(int)( (int)expbase * 1.2 )`と先に整数に丸めてから1.2倍する必要があるようです。

**Comment by andanteyk** [comment]
ご指摘ありがとうございます。
現行の作業が終わり次第修正します。

**Comment by andanteyk** [comment]
ee3ba1aeb02d5087d3a6aba9ce0f89facebf4f02 で修正しました。
