### ISSUE TITLE
DateTime Parse Error

### ISSUE THREAD

**Issue by chronomeister** [andanteyk/ElectronicObserver#51]
Records were always generating errors. Turns out .NET's DateTime.ToString() is a bit strange. Note the system Short Date in all these.

Here's how I think you expected dates to be:
![standard](https://cloud.githubusercontent.com/assets/13879793/9421719/5b9f0970-483e-11e5-8f8c-82ef155b52b7.png)
Here's how my dates were:
![mine](https://cloud.githubusercontent.com/assets/13879793/9421722/6ba301e6-483e-11e5-9e2e-d836bf8544bf.png)
One way to fix would be get the separators from the system:
![fix](https://cloud.githubusercontent.com/assets/13879793/9421877/ad6955e0-4842-11e5-957d-87f05ccc9e63.png)
And it would still work the original way:
![fixv2](https://cloud.githubusercontent.com/assets/13879793/9421878/b1eceee2-4842-11e5-96e1-988c5732c623.png)

**Comment by andanteyk** [comment]
Thank you for your information.
Perhaps I fixed it at https://github.com/andanteyk/ElectronicObserver/blob/ee3ba1aeb02d5087d3a6aba9ce0f89facebf4f02/ElectronicObserver/Utility/Mathematics/DateTimeHelper.cs#L197, but not been able to test in my environment.
Please tell me again if it don't work.

**Comment by chronomeister** [comment]
No that would fix my problem.
![fixv2](https://cloud.githubusercontent.com/assets/13879793/9425222/517dca22-48ce-11e5-9406-d63ddec1acd8.png)
![fix](https://cloud.githubusercontent.com/assets/13879793/9425223/54833aa4-48ce-11e5-9310-a611ad3c67cc.png)
It works either way now. Your fix makes output more consistent, too.
