### ISSUE TITLE
Screenshot Failure

### ISSUE THREAD

**Issue by nagatoyk** [andanteyk/ElectronicObserver#55]
![截图失败](http://ww2.sinaimg.cn/mw1024/a15b4afegw1ewydx2gikuj20cv00tdfr)

**Comment by andanteyk** [comment]
When you play KanColle, do you have direct access to `mainD2.swf` ?

**Comment by nagatoyk** [comment]
I use agents have local cache, and this theme fail problem occasionally, but do not know how to reproduce the problem, a problem occurs, I always reboot after the software is fully loaded until KanColle login screen test theme is successful, only click on the login, I think this theme this button, you can light up his theme, if not shot on gray.

**Comment by andanteyk** [comment]
If this problem occurs rarely and it is resolved by reloading, I also experienced its problem.
But, I don't have any idea to fix it.

**Comment by andanteyk** [comment]
Fixed at ver. 2.1.0.
