### ISSUE TITLE
failed to load time zone info

### ISSUE THREAD

**Issue by zhailingzy** [andanteyk/ElectronicObserver#56]
When open show error {"The time zone ID 'Tokyo Standard Time' was found on the local computer, but the registry information was corrupt."}
The problem is for unknown reason The program (and I) cannot find correct time zone info in registry.
Is it better to handle this exception and not hard code Tokyo standard time in program?
To fix this problem and enjoy the tool I've downloaded the source and changed the time zone setting to my current time zone.

**Comment by zhailingzy** [comment]
test @andanteyk

**Comment by andanteyk** [comment]
This program (and KanColle) is intended for use in Japan.
*Basically*, I can't be corresponding about the problem that occurred when using abroad.

Maybe fixed it at 68e3b9d0489a56e9343cf1ba011bc84e3307eb77 .
I can't check that it works properly; if you can test it, please report me it works or not.

**Comment by zhailingzy** [comment]
Sorry but the true problem is missing registry entry(not use abroad). I thought the program should handle this exception and avoid to hardcode somethinng in it.
However I just want to tell you about this issue. And thanks for this useful tool.

**Comment by andanteyk** [comment]
Thank you for information.

1.
Sorry, I had forgotten it.
I think that its clock should display in Tokyo Standard Time ( = time of KanColle servers ).
It is for playing KanColle, not for normal purposes, so it needs to display the same time as the server.

2.
OK.

**Comment by andanteyk** [comment]
Fixed it at 6b1b24d047179e4d30be8f7cd94ba13beaf3faf7 .
