### ISSUE TITLE
new encounted enemyship parameters could't be recorded

### ISSUE THREAD

**Issue by herix001** [andanteyk/ElectronicObserver#58]
function GameStart and BattleStart in ShipParameterRecord.cs

if ( param == null ) {
					param = new ShipParameterElement();
					param.ShipID = (int)elem.api_id;
				}

 this[(int)elem.api_id]=param;//need added in if{}

**Comment by andanteyk** [comment]
Thank you for your information.
I fixed it at 61ca197412a2dd01beb652cd1fe8b168f03554bc .
