### ISSUE TITLE
ブラウザが真っ白になるあるいは通信が非常に遅くなる

### ISSUE THREAD

**Issue by fujieda** [andanteyk/ElectronicObserver#59]
VirtualBoxかVMwareがインストールされていて、かつIEのプロキシ設定で「設定を自動的に検出する」がチェックされていると発生する問題です。PCでAndroidのゲームを動かすために使われている、GenyMotionがVirtualBoxを含んでいるため影響範囲が拡大したようです。

解決策は、Nekoxyのアップストリーム設定でSystemProxyではなくDirectAccessを指定することです。SystemProxyは、航海日誌などとの連携をスムーズにするために実装されました。しかし、現状でうまく機能しているとは言い難いですし、むしろ被害が大きいのでDirectAccessにすることをお勧めします。

アップストリーム設定でSystemProxyを指定すると、NekoxyはIEのプロキシ設定から上流のプロキシのアドレスを取得してそちらにリクエストを転送します。上記の環境では、Nekoxyは謎のプロキシのアドレスを取得して、そちらにリクエストを転送します。

リクエストを受け取った謎のプロキシは、なぜかもう一度40620にリクエストを転送するため、ループができてしまいます。ループをぐるぐる回ってephemeralポートを使い切ったところで、最後のプロキシが外にリクエストを投げるので、通信が非常に遅くなる問題が生じます。

謎のプロキシの正体が何なのかはまだわかりませんが、DirectAccessを指定することで、このプロキシにリクエストを転送することがなくなるので問題が解決します。

**Comment by andanteyk** [comment]
なるほど、了解しました。
なるべく早く修正します。

**Comment by andanteyk** [comment]
9feb0eb2043ec3e7e13cf54943ff11349dc2d324 で修正・調整しました。
貴重な情報をありがとうございました。
