### ISSUE TITLE
上流プロキシ設定が2.0以降うまく動作しません、特にHTTPS

### ISSUE THREAD

**Issue by Cosmius** [andanteyk/ElectronicObserver#60]
おそらく、Nekoxy 移行が原因だと考えてます

**Comment by andanteyk** [comment]
[Nekoxy は HTTPS に対応していないようです。](https://github.com/veigr/Nekoxy/blob/master/README.md#%E5%88%B6%E9%99%90%E4%BA%8B%E9%A0%85)
なお、Nekoxy への移行を行ったのは FiddlerCore にライセンス上の問題があったためですので、FiddlerCore に戻すつもりはありません。
対応できるかはわかりませんが、現在の通信環境(どのツールを併用しているか、など)を教えていただけるとありがたいです。

**Comment by Cosmius** [comment]
それは残念なり、でも、Nexory経由でないtrafficの部分なら、プロキシ設定できないでしょうか？

HTTPS traffic -> upstream proxy
HTTP -> Nekoxy -> upstream proxy
というようにはダメでしょうか？

**Comment by andanteyk** [comment]
#62 で解決しました。
