### ISSUE TITLE
Condition timer not working correctly

### ISSUE THREAD

**Issue by xiaozhikang0916** [andanteyk/ElectronicObserver#66]
After finishing a battle with combined fleet and come back to home port, ships in fleet 2 are actually in yellow-face condition, but the condition timer remind me that they are recover from bad-condition.
![qq 20160523222533](https://cloud.githubusercontent.com/assets/8273026/15474206/6ba678b8-2136-11e6-92f3-17edb3fc4a44.png)

If I refresh by coming back to home port, the timer work fine then
![qq 20160523222543](https://cloud.githubusercontent.com/assets/8273026/15474237/8afbb5de-2136-11e6-8489-f86c8fbebf7e.png)
The timer of fleet 1 seems work fine all the time.

**Comment by andanteyk** [comment]
Thank you for your information.
I also have experienced this issue, but I can't find the cause yet.
I'm trying to fix it.

**Comment by xiaozhikang0916** [comment]
Similarly issue found

1. fleet in red-face condition
2. save in fleet record($1) and expend other fleet record($2)
3. use $2 to finish some battles, may be in around 38 condition
4. expend $1, found it in yellow-face condition, but informed will be recovered in 3 minutes
![ecuhc fix 6kmflv _1o2q](https://cloud.githubusercontent.com/assets/8273026/17739387/84075da8-64c7-11e6-9ee6-db2e633ef5a4.png)

**Comment by andanteyk** [comment]
In 909d236d7becbb6cb4c0d9675970d253d8b94ef6 , I have completely rewrote the fatigue level management system.
Therefore, this problem has disappeared.
If a similar problem occurs with a new code, please contact me again though it is sorry to trouble you.

---


909d236d7becbb6cb4c0d9675970d253d8b94ef6 において、疲労度管理システムを全面的に書き直しました。
そのためこの問題は消滅しました。
新しいコードでも同様の問題が発生した場合、お手数ですが再度ご連絡ください。
