### ISSUE TITLE
Can we separate "その他" from "デイリー任務を表示" in the Quest Window?

### ISSUE THREAD

**Issue by ccxcxd** [andanteyk/ElectronicObserver#70]
I really don't want to complete the new "「熟練搭乗員」養成" quarterly quest, but it keep showing up in the Quest Window. I know I can hide it if I uncheck "デイリー任務を表示", but it will hide all daily quests as well. Can we have a separate checkbox to just hide the "その他任務" ?

Thanks

**Comment by andanteyk** [comment]
Implemented in 46637f6aa3157f6542fd5a819735166b74642519.
It will be available from the next version.
