### ISSUE TITLE
[表示]-[入渠] : Ship name displays higher if ellipsised.

### ISSUE THREAD

**Issue by RadarNyan** [andanteyk/ElectronicObserver#79]
If ship name is too long to fit in the panel, it will be ellipsised. But there seems to be a [BUG](http://stackoverflow.com/questions/24447344/autoellipsis-true-affects-the-vertical-positioning-of-the-text) that when a label is set to AutoEllipsis = true and ellipsis happens, it will be aligned to top regardless of property given.

![74eo-2 4 3-issue-001](https://cloud.githubusercontent.com/assets/2091529/19411106/b3e5cb3a-9335-11e6-94d2-fbb92be9dacf.png)
I don't like the idea of setting UseCompatibleTextRendering so I tried to [fix this](https://github.com/RadarNyan/ElectronicObserver/commit/aaff9ae5dfe161b883fb6d123819164a171b0f80) by ellipsising the string myself, and it seems to be working (left one in the picture above) but I don't really like what I've done, maybe you can come up with a better solution (or more legit code).

**Comment by andanteyk** [comment]
This issue was resolved at 92d0259c1c9e95e36c084f8d570f7219a751bbdc .
I changed Label into ImageLabel.
In addition, "..." was taking a wasted space, it has been omitted.
