### ISSUE TITLE
Tool Window (like "装備一覧") - window disappear when click on "File" menu.

### ISSUE THREAD

**Issue by RadarNyan** [andanteyk/ElectronicObserver#83]
![74eo-bug-tool-window](https://cloud.githubusercontent.com/assets/2091529/19619552/f6c248ce-98a4-11e6-9c3a-9de5a9da6c1e.gif)

Sometimes when I click the "File" menu of some tool window (eg: "装備一覧", "舰船图鉴" ) the menu would display but the tool window disappears. This bug doesn't happen right after I start 74EO, and I can't find a way to actively trigger it.

I found a workaround to make the window stop disappearing: enable and disable "Always on top" for 74EO. See the GIF on top for the behavior of the bug and the workaround.

**Comment by RadarNyan** [comment]
After some internet search, I found that this appears to be a bug in C# framework.
[Strange Bug with .NET 4.0/4.5 WinForms MenuStrip Stealing Focus](http://stackoverflow.com/questions/14058222/strange-bug-with-net-4-0-4-5-winforms-menustrip-stealing-focus)

There is workaround provided in the link above but I couldn't find a way to proper implent it, maybe you'll have some more luck?

If this bug can not be workaround, I'll go with the hotfix but I'd really like this to be fixed without applying the hotfix, here's why: I already have my Windows 7 up-to-date (which means, I have all the Windows Update labeled as "Important" installed) apparently this hotfix for .net is not included in any one of them, and accroading to the stackoverflow page it seems this bug also affects other versions of Windows?

**Comment by RadarNyan** [comment]
A partial workaround: https://github.com/RadarNyan/ElectronicObserver/commit/1410fb09c193fbcf5b73ade9067072fdb9576cd0

**Comment by andanteyk** [comment]
I do not know if this commit corrected this problem because the problem was not reproducible.
However, there seems to be no side effects, so I would like to merge and wait and see.
