### ISSUE TITLE
HP bar not shown correctly in combined fleet in night battle

### ISSUE THREAD

**Issue by xiaozhikang0916** [andanteyk/ElectronicObserver#89]
![qq 20161119122948](https://cloud.githubusercontent.com/assets/8273026/20453034/e3e3841a-ae53-11e6-8460-31c94529674e.png)
機動艦隊 Night battle, Not Boss point

**Comment by andanteyk** [comment]
もし戦闘時の API ログが残っているのであれば、送信していただけると助かります。
(`*date*S@api_req_combined_battle@midnight_battle.json`)

**Comment by xiaozhikang0916** [comment]
It is an error from server, `api_maxhps_combined` is set as `now_hps` after battle day.
Zip below is logs of battle day and battle night.
[KCAPI_E3.zip](https://github.com/andanteyk/ElectronicObserver/files/601280/KCAPI_E3.zip)

**Comment by andanteyk** [comment]
ありがとうございます。確かにデータがおかしいようです。
とりあえず、艦これ本体側の修正を待つことにします。

**Comment by xiaozhikang0916** [comment]
Since this parameter is not shown in normal client, I don't know if the server would fix it.
However, I try to fix it with reading max hp from fleet data. #90 
If the server fix this, you can remove the code.
