### ISSUE TITLE
ブラウザ：ズーム「ぴったり」が動作しない

### ISSUE THREAD

**Issue by andanteyk** [andanteyk/ElectronicObserver#98]

**Comment by RadarNyan** [comment]
Need more info. I didn't touch this part of code (I've confirmed it by checking with git diff) and it works on my custom build. However I did break stylesheet for IE8 though (as described in #96 and fix provided)

**Comment by andanteyk** [comment]
![default](https://cloud.githubusercontent.com/assets/4958081/20625622/df82e18c-b357-11e6-8564-9f0d37eb0f74.PNG)
![2](https://cloud.githubusercontent.com/assets/4958081/20625623/dfc16c18-b357-11e6-8d8b-6541a3f9c75f.PNG)

Style sheet : applied
Browser Version: 11001
(設定→サブウィンドウ→ブラウザ2→ブラウザバージョン)

**Comment by RadarNyan** [comment]
Ok I get it... 457cc18 should already fixed this (by adding `!important` to height & width to override inline style in the original page) My bad, should have made that commit a separate pull request. Just cherry-pick it and see how it goes.
